// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Preorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Preorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201312111632514_Preorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
