// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class orderAcc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orderAcc));
        
        string IMigrationMetadata.Id
        {
            get { return "201312162028188_orderAcc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
