// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Orders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Orders));
        
        string IMigrationMetadata.Id
        {
            get { return "201312121456182_Orders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
