// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SkuInventoryImplement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkuInventoryImplement));
        
        string IMigrationMetadata.Id
        {
            get { return "201401221217094_SkuInventoryImplement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
