// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NamePreorderFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NamePreorderFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201410061327540_Name=PreorderFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
