// <auto-generated />
namespace AstCore.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SkuImplement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SkuImplement));
        
        string IMigrationMetadata.Id
        {
            get { return "201401221843126_SkuImplement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
